import { GetStaticProps } from "next";
import Head from "next/head";
import { PostData } from "../src/domain/posts/post";

export type HomeProps = {
    posts: PostData[];
};

export default function Home({ posts }: HomeProps) {
    return (
        <>
            <Head>
                <title>Next Blog</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h2>Next Blog with Strapi</h2>

                {posts.map((post) => {
                    return (
                        <div key={post.id}>
                            <p>{post.attributes.title}</p>
                            <br />
                            <hr />
                        </div>
                    );
                })}
            </main>
        </>
    );
}

export const getStaticProps: GetStaticProps<{
    posts: HomeProps[];
}> = async () => {
    const res = await fetch(
        "https://strapi-production-0af2.up.railway.app/api/posts?populate=%2A"
    );

    const data = await res.json().then(({ data }) => data);
    const posts: HomeProps[] = data;

    return {
        props: {
            posts,
        },
    };
};
